### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Bandesss** [GeekbeeGER/WindowsGSM.ArmaReforger#1]
Hello Palworld works and Enshoured but not Arma Reforger that's what it looks like
![start](https://github.com/GeekbeeGER/WindowsGSM.ArmaReforger/assets/50829319/0f446483-a2db-4dea-b1ed-a9bb7f9b9009)
Can you Help me?=

Greets

**Comment by GeekbeeGER** [comment]
didnt see error???

**Comment by Bandesss** [comment]
This is the start protocol from my server there is much more than in the picture above
Do you know what I mean ?
https://prnt.sc/H2S5UQgVgHdR

**Comment by GeekbeeGER** [comment]
It just says that the game files are checked, it's not an error and you use a bat that is not supported by the plugin's exe file...

**Comment by Bandesss** [comment]
OP thanks, what did I do wrong then?

**Comment by GeekbeeGER** [comment]
bro you using the batchfile!  public override string StartPath => "ArmaReforgerServer.exe"; // Game server start path, for ArmaReforger, it is ArmaReforgerserver.exe stop using this batch!

**Comment by Bandesss** [comment]
The first picture was only with their program what do I not understand ?

**Comment by GeekbeeGER** [comment]
where does the batch file come from then there is none by default!

i do not give support for something like this it has nothing to do with the plugin so i will close your requests now
